/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package HMC_Vista;

import HMC_Modelo.HMC_Conexion;
import javax.swing.JOptionPane;

/**
 *
 * @author Benjamin
 */
public class HMC_detalleEmpleado extends javax.swing.JPanel {

    /**
     * Creates new form HMC_detalleEmpleado
     */
    public HMC_detalleEmpleado() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtNombreBucar = new javax.swing.JTextField();
        txtIdBuscar = new javax.swing.JTextField();
        txtApellidoPatBuscar = new javax.swing.JTextField();
        txtApellidoMarBuscar = new javax.swing.JTextField();
        txtEmailBuscar = new javax.swing.JTextField();
        txtDepBuscar = new javax.swing.JTextField();
        txtPuestoBuscar = new javax.swing.JTextField();
        txtSalarioBuscar = new javax.swing.JTextField();
        txtNacimientoBuscar = new javax.swing.JTextField();
        txtContratacionBuscar = new javax.swing.JTextField();
        txtActivoBuscar = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtTelefonoBuscar = new javax.swing.JTextField();
        label1 = new java.awt.Label();
        btnBuscarEmpleado = new javax.swing.JButton();
        btnNuevoEmpleado = new javax.swing.JButton();
        btnEliminarEmpleado = new javax.swing.JButton();
        btnGuardarEmpleado = new javax.swing.JButton();
        btnEditarEmpleado = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Empleado");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("ID");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Nombre");

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Apellido paterno");

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Apellido materno");

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Departamento");

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Email");

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Salario");

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Puesto");

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Fecha de nacimiento");

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("Fecha de contratación");

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("Activo");

        txtNombreBucar.setEditable(false);

        txtApellidoPatBuscar.setEditable(false);

        txtApellidoMarBuscar.setEditable(false);

        txtEmailBuscar.setEditable(false);

        txtDepBuscar.setEditable(false);

        txtPuestoBuscar.setEditable(false);

        txtSalarioBuscar.setEditable(false);
        txtSalarioBuscar.addActionListener(this::txtSalarioBuscarActionPerformed);

        txtNacimientoBuscar.setEditable(false);

        txtContratacionBuscar.setEditable(false);

        txtActivoBuscar.setEditable(false);

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel13.setText("Telefono");

        txtTelefonoBuscar.setEditable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtIdBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTelefonoBuscar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNombreBucar, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                            .addComponent(txtApellidoPatBuscar)
                            .addComponent(txtApellidoMarBuscar)
                            .addComponent(txtEmailBuscar)
                            .addComponent(txtDepBuscar)
                            .addComponent(txtPuestoBuscar)
                            .addComponent(txtSalarioBuscar)
                            .addComponent(txtNacimientoBuscar)
                            .addComponent(txtContratacionBuscar)
                            .addComponent(txtActivoBuscar))))
                .addGap(29, 29, 29))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtIdBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombreBucar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtApellidoPatBuscar))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 18, Short.MAX_VALUE))
                    .addComponent(txtApellidoMarBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 18, Short.MAX_VALUE))
                    .addComponent(txtEmailBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtDepBuscar))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 19, Short.MAX_VALUE))
                    .addComponent(txtPuestoBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtSalarioBuscar))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtNacimientoBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtContratacionBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtActivoBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 18, Short.MAX_VALUE))
                    .addComponent(txtTelefonoBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12))
        );

        label1.setText("Puede busacar por ID.");

        btnBuscarEmpleado.setText("BUSCAR");
        btnBuscarEmpleado.addActionListener(this::btnBuscarEmpleadoActionPerformed);

        btnNuevoEmpleado.setText("NUEVO");
        btnNuevoEmpleado.addActionListener(this::btnNuevoEmpleadoActionPerformed);

        btnEliminarEmpleado.setForeground(new java.awt.Color(255, 51, 51));
        btnEliminarEmpleado.setText("ELIMINAR");
        btnEliminarEmpleado.setEnabled(false);
        btnEliminarEmpleado.addActionListener(this::btnEliminarEmpleadoActionPerformed);

        btnGuardarEmpleado.setText("GUARDAR");
        btnGuardarEmpleado.setEnabled(false);
        btnGuardarEmpleado.addActionListener(this::btnGuardarEmpleadoActionPerformed);

        btnEditarEmpleado.setText("EDITAR");
        btnEditarEmpleado.setEnabled(false);
        btnEditarEmpleado.addActionListener(this::btnEditarEmpleadoActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNuevoEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGuardarEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminarEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditarEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(76, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(btnBuscarEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(btnNuevoEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(btnEditarEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(btnGuardarEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEliminarEmpleado)))
                .addContainerGap(77, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtSalarioBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSalarioBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSalarioBuscarActionPerformed

    // Método para transformar AAAA-MM-DD HH:mm:ss a DD/MM/AAAA
    private String formatearFecha(String fechaBD) {
        if (fechaBD.isEmpty()) {
            return "";
        }
        try {
            // 1. Quitamos la hora si existe (cortamos por el espacio)
            String soloFecha = fechaBD.split(" ")[0];
            // 2. Dividimos los componentes del año-mes-dia
            String partes[] = soloFecha.split("-");
            if (partes.length == 3) {
                // 3. Reordenamos a DD/MM/AAAA
                return partes[2] + "/" + partes[1] + "/" + partes[0];
            }
        } catch (Exception e) {
            return fechaBD; // Si algo falla, devuelve la original
        }
        return fechaBD;
    }

    public void resetearFormulario() {
        // 1. Limpiar todos los textos
        txtIdBuscar.setText("");
        txtNombreBucar.setText("");
        txtApellidoPatBuscar.setText("");
        txtApellidoMarBuscar.setText("");
        txtEmailBuscar.setText("");
        txtDepBuscar.setText("");
        txtPuestoBuscar.setText("");
        txtSalarioBuscar.setText("");
        txtNacimientoBuscar.setText("");
        txtContratacionBuscar.setText("");
        txtActivoBuscar.setText("");
        txtTelefonoBuscar.setText("");

        // 2. Bloquear los campos de texto (para que no escriban sin darle a 'Nuevo')
        txtIdBuscar.setEnabled(true); // El ID se queda activo para poder buscar
        txtNombreBucar.setEnabled(false);
        txtApellidoPatBuscar.setEnabled(false);
        txtApellidoMarBuscar.setEnabled(false);
        txtEmailBuscar.setEnabled(false);
        txtTelefonoBuscar.setEnabled(false);
        txtSalarioBuscar.setEnabled(false);
        txtNacimientoBuscar.setEnabled(false);
        txtContratacionBuscar.setEnabled(false);
        txtDepBuscar.setEnabled(false);
        txtPuestoBuscar.setEnabled(false);
        txtActivoBuscar.setEnabled(false);

        // 3. Gestionar los botones
        btnNuevoEmpleado.setEnabled(true);    // Puede crear uno nuevo
        btnBuscarEmpleado.setEnabled(true);   // Puede buscar
        btnGuardarEmpleado.setEnabled(false); // No puede guardar nada vacío

        // 4. Cursor al campo de búsqueda
        txtIdBuscar.requestFocusInWindow();
    }

    private void btnBuscarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarEmpleadoActionPerformed
        HMC_Conexion con = new HMC_Conexion();

        int iDEmpleadoBuscar = Integer.parseInt(txtIdBuscar.getText());

        String empleadoEncontrado = con.buscarEmpleadoporId(iDEmpleadoBuscar);

        if (empleadoEncontrado != null && !empleadoEncontrado.isEmpty()) {
            String empleadoEncontradoBD[] = empleadoEncontrado.split("!");

            // Función auxiliar interna para limpiar nulos
            // (Puedes ponerla fuera del método si prefieres)
            java.util.function.Function<String, String> limpiar = (str)
                    -> (str == null || str.equals("null")) ? "" : str;

            txtIdBuscar.setText(limpiar.apply(empleadoEncontradoBD[0]));
            txtNombreBucar.setText(limpiar.apply(empleadoEncontradoBD[1]));
            txtApellidoPatBuscar.setText(limpiar.apply(empleadoEncontradoBD[2]));
            txtApellidoMarBuscar.setText(limpiar.apply(empleadoEncontradoBD[3]));
            txtEmailBuscar.setText(limpiar.apply(empleadoEncontradoBD[4]));
            txtDepBuscar.setText(limpiar.apply(empleadoEncontradoBD[5]));
            txtPuestoBuscar.setText(limpiar.apply(empleadoEncontradoBD[6]));
            txtSalarioBuscar.setText(limpiar.apply(empleadoEncontradoBD[7]));

            // --- MANEJO DE FECHAS (Nacimiento es el índice 8, Contratación el 9) ---
            txtNacimientoBuscar.setText(formatearFecha(limpiar.apply(empleadoEncontradoBD[8])));
            txtContratacionBuscar.setText(formatearFecha(limpiar.apply(empleadoEncontradoBD[9])));

            txtActivoBuscar.setText(limpiar.apply(empleadoEncontradoBD[10]));
            txtTelefonoBuscar.setText(limpiar.apply(empleadoEncontradoBD[11]));
            btnEditarEmpleado.setEnabled(true);
            btnEliminarEmpleado.setEnabled(true);
        } else {
            JOptionPane.showMessageDialog(this, "Empleado no encontrado!.");
            txtIdBuscar.setText("");
            txtNombreBucar.setText("");
            txtApellidoPatBuscar.setText("");
            txtApellidoMarBuscar.setText("");
            txtEmailBuscar.setText("");
            txtDepBuscar.setText("");
            txtPuestoBuscar.setText("");
            txtSalarioBuscar.setText("");
            txtNacimientoBuscar.setText("");
            txtContratacionBuscar.setText("");
            txtActivoBuscar.setText("");
            txtTelefonoBuscar.setText("");
            txtIdBuscar.requestFocusInWindow();

        }
    }//GEN-LAST:event_btnBuscarEmpleadoActionPerformed

    private void btnNuevoEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoEmpleadoActionPerformed
        btnBuscarEmpleado.setEnabled(false);
        btnGuardarEmpleado.setEnabled(true);
        txtIdBuscar.setText("");
        txtNombreBucar.setText("");
        txtApellidoPatBuscar.setText("");
        txtApellidoMarBuscar.setText("");
        txtEmailBuscar.setText("");
        txtDepBuscar.setText("");
        txtPuestoBuscar.setText("");
        txtSalarioBuscar.setText("");
        txtIdBuscar.requestFocusInWindow();
        txtNacimientoBuscar.setText("");
        txtContratacionBuscar.setText("");
        txtActivoBuscar.setText("");
        txtTelefonoBuscar.setText("");
        //Activar txt
        txtIdBuscar.setText("");
        txtIdBuscar.setEnabled(false);
        txtNombreBucar.requestFocusInWindow();
        txtNombreBucar.setEnabled(true);
        txtApellidoPatBuscar.setEnabled(true);
        txtApellidoMarBuscar.setEnabled(true);
        txtEmailBuscar.setEnabled(true);
        txtDepBuscar.setEnabled(true);
        txtPuestoBuscar.setEnabled(true);
        txtSalarioBuscar.setEnabled(true);
        txtNacimientoBuscar.setEnabled(true);
        txtContratacionBuscar.setEnabled(true);
        txtActivoBuscar.setEnabled(true);
        txtTelefonoBuscar.setEnabled(true);
        btnNuevoEmpleado.setEnabled(false);

        txtNombreBucar.setEditable(true);
        txtApellidoPatBuscar.setEditable(true);
        txtApellidoMarBuscar.setEditable(true);
        txtEmailBuscar.setEditable(true);
        txtDepBuscar.setEditable(true);
        txtPuestoBuscar.setEditable(true);
        txtSalarioBuscar.setEditable(true);
        txtNacimientoBuscar.setEditable(true);
        txtContratacionBuscar.setEditable(true);
        txtActivoBuscar.setEditable(true);
        txtTelefonoBuscar.setEditable(true);
    }//GEN-LAST:event_btnNuevoEmpleadoActionPerformed

    private void btnEliminarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarEmpleadoActionPerformed
        HMC_Conexion con = new HMC_Conexion();

        int iDEmpleadoBuscar = Integer.parseInt(txtIdBuscar.getText());
        
        try {
            
            boolean eliminarEmpleado = con.eliminarEmpleado(iDEmpleadoBuscar);
            JOptionPane.showMessageDialog(this, "Usuario eliminado con ID: " + iDEmpleadoBuscar);
            resetearFormulario();
            btnEditarEmpleado.setEnabled(false);
            
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al eliminar usuario: " + e);
        }
    }//GEN-LAST:event_btnEliminarEmpleadoActionPerformed

    private void btnGuardarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarEmpleadoActionPerformed

        try {
            // =========================
            // 1. DATOS GENERALES
            // =========================
            String nombre = txtNombreBucar.getText().trim();
            String apePat = txtApellidoPatBuscar.getText().trim();
            String apeMat = txtApellidoMarBuscar.getText().trim();
            String email = txtEmailBuscar.getText().trim();
            String tel = txtTelefonoBuscar.getText().trim();
            String fechaNac = txtNacimientoBuscar.getText().trim();
            String fechaCon = txtContratacionBuscar.getText().trim();

            // =========================
            // 2. VALIDACIÓN BÁSICA
            // =========================
            if (nombre.isEmpty() || apePat.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Nombre y Apellido son obligatorios");
                return;
            }

            // =========================
            // 3. PARSEO SEGURO
            // =========================
            double salario = parseDoubleSeguro(txtSalarioBuscar.getText());

            if (salario < 0) {
                JOptionPane.showMessageDialog(this, "Salario inválido");
                return;
            }

            HMC_Conexion con = new HMC_Conexion();
            boolean exito = false;

            // =========================
            // 4. DEFINIR OPERACIÓN
            // =========================
            boolean esNuevo = txtIdBuscar.getText().trim().isEmpty();

            // =========================
            // 5. INSERT
            // =========================
            if (esNuevo) {

                System.out.println("Estas creando un usuario");

                int idDep = parseEnteroSeguro(txtDepBuscar.getText());
                int idPuesto = parseEnteroSeguro(txtPuestoBuscar.getText());

                if (idDep <= 0 || idPuesto <= 0) {
                    JOptionPane.showMessageDialog(this, "Departamento y Puesto deben ser válidos");
                    return;
                }

                exito = con.insertarEmpleado(
                        nombre, apePat, apeMat,
                        email, tel, fechaNac, fechaCon,
                        salario, idDep, idPuesto
                );

                if (exito) {
                    JOptionPane.showMessageDialog(this, "Empleado creado exitosamente");
                }

            } else {
                // =========================
                // 6. UPDATE
                // =========================

                System.out.println("Estas EDITANDO un usuario");

                int idExistente = parseEnteroSeguro(txtIdBuscar.getText());

                if (idExistente <= 0) {
                    JOptionPane.showMessageDialog(this, "ID inválido");
                    return;
                }

                exito = con.actualizarEmpleado(
                        idExistente,
                        nombre,
                        apePat,
                        apeMat,
                        tel,
                        salario
                );

                if (exito) {
                    JOptionPane.showMessageDialog(this, "Empleado actualizado exitosamente");
                    btnEditarEmpleado.setEnabled(false);
                }
            }

            // =========================
            // 7. LIMPIAR FORMULARIO
            // =========================
            if (exito) {
                resetearFormulario();
            }

        } catch (Exception e) {

            JOptionPane.showMessageDialog(
                    this,
                    "Error al guardar: " + e.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE
            );

            e.printStackTrace();
        }

    }//GEN-LAST:event_btnGuardarEmpleadoActionPerformed

    private int parseEnteroSeguro(String valor) {
        try {
            if (valor == null || valor.trim().isEmpty()) {
                return 0;
            }
            return Integer.parseInt(valor.trim());
        } catch (NumberFormatException e) {
            return -1;
        }
    }

    private double parseDoubleSeguro(String valor) {
        try {
            if (valor == null || valor.trim().isEmpty()) {
                return 0;
            }
            return Double.parseDouble(valor.trim());
        } catch (NumberFormatException e) {
            return -1;
        }
    }


    private void btnEditarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarEmpleadoActionPerformed
        btnNuevoEmpleado.setEnabled(false);
        btnBuscarEmpleado.setEnabled(false);
        btnGuardarEmpleado.setEnabled(true);

        txtIdBuscar.setEnabled(false);
        txtNombreBucar.requestFocusInWindow();
        txtNombreBucar.setEnabled(true);
        txtApellidoPatBuscar.setEnabled(true);
        txtApellidoMarBuscar.setEnabled(true);
        txtEmailBuscar.setEnabled(false);
        txtDepBuscar.setEnabled(false);
        txtPuestoBuscar.setEnabled(false);
        txtSalarioBuscar.setEnabled(true);
        txtNacimientoBuscar.setEnabled(false);
        txtContratacionBuscar.setEnabled(false);
        txtActivoBuscar.setEnabled(false);
        txtTelefonoBuscar.setEnabled(true);

        txtNombreBucar.setEditable(true);
        txtApellidoPatBuscar.setEditable(true);
        txtApellidoMarBuscar.setEditable(true);
        txtTelefonoBuscar.setEditable(true);
        txtSalarioBuscar.setEditable(true);
    }//GEN-LAST:event_btnEditarEmpleadoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarEmpleado;
    private javax.swing.JButton btnEditarEmpleado;
    private javax.swing.JButton btnEliminarEmpleado;
    private javax.swing.JButton btnGuardarEmpleado;
    private javax.swing.JButton btnNuevoEmpleado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private java.awt.Label label1;
    private javax.swing.JTextField txtActivoBuscar;
    private javax.swing.JTextField txtApellidoMarBuscar;
    private javax.swing.JTextField txtApellidoPatBuscar;
    private javax.swing.JTextField txtContratacionBuscar;
    private javax.swing.JTextField txtDepBuscar;
    private javax.swing.JTextField txtEmailBuscar;
    private javax.swing.JTextField txtIdBuscar;
    private javax.swing.JTextField txtNacimientoBuscar;
    private javax.swing.JTextField txtNombreBucar;
    private javax.swing.JTextField txtPuestoBuscar;
    private javax.swing.JTextField txtSalarioBuscar;
    private javax.swing.JTextField txtTelefonoBuscar;
    // End of variables declaration//GEN-END:variables
}
