/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package HMC_Vista;

/**
 *
 * @author Benjamin
 */
public class HMC_Principal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(HMC_Principal.class.getName());

    /**
     * Creates new form HMC_Principal
     */
    public HMC_Principal() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        jPopupMenu3 = new javax.swing.JPopupMenu();
        jPopupMenu4 = new javax.swing.JPopupMenu();
        jPopupMenu5 = new javax.swing.JPopupMenu();
        jPopupMenu6 = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        content = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuRH = new javax.swing.JMenu();
        menuBuscarEmpleado = new javax.swing.JMenuItem();
        menuNomina = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1393, Short.MAX_VALUE)
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 885, Short.MAX_VALUE)
        );

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        menuRH.setText("RH");
        menuRH.addActionListener(this::menuRHActionPerformed);

        menuBuscarEmpleado.setText("Empledo");
        menuBuscarEmpleado.addActionListener(this::menuBuscarEmpleadoActionPerformed);
        menuRH.add(menuBuscarEmpleado);

        menuNomina.setText("Nomina");
        menuNomina.addActionListener(this::menuNominaActionPerformed);
        menuRH.add(menuNomina);

        jMenuBar1.add(menuRH);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(content, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(content, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuBuscarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuBuscarEmpleadoActionPerformed
            HMC_detalleEmpleado detalle = new HMC_detalleEmpleado();

            // 1. Definir el tamaño del panel igual al del contenedor
            detalle.setSize(this.content.getWidth(), this.content.getHeight());
            detalle.setLocation(0,0);

            // 2. Limpiar el contenedor principal y agregar el nuevo panel
            this.content.removeAll();
            this.content.add(detalle);

            // 3. Refrescar la interfaz para que se pinte el cambio
            this.content.revalidate();
            this.content.repaint();
    }//GEN-LAST:event_menuBuscarEmpleadoActionPerformed

    private void menuNominaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuNominaActionPerformed
            HMC_Nomina detalle = new HMC_Nomina();

            // 1. Definir el tamaño del panel igual al del contenedor
            detalle.setSize(this.content.getWidth(), this.content.getHeight());
            detalle.setLocation(0,0);

            // 2. Limpiar el contenedor principal y agregar el nuevo panel
            this.content.removeAll();
            this.content.add(detalle);

            // 3. Refrescar la interfaz para que se pinte el cambio
            this.content.revalidate();
            this.content.repaint();
    }//GEN-LAST:event_menuNominaActionPerformed

    private void menuRHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuRHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuRHActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new HMC_Principal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel content;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JPopupMenu jPopupMenu3;
    private javax.swing.JPopupMenu jPopupMenu4;
    private javax.swing.JPopupMenu jPopupMenu5;
    private javax.swing.JPopupMenu jPopupMenu6;
    private javax.swing.JMenuItem menuBuscarEmpleado;
    private javax.swing.JMenuItem menuNomina;
    public javax.swing.JMenu menuRH;
    // End of variables declaration//GEN-END:variables
}
