/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package HMC_Vista;

import HMC_Modelo.HMC_Conexion;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Benjamin
 */
public class HMC_Login extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(HMC_Login.class.getName());

    /**
     * Creates new form HMC_Login
     */
    public HMC_Login() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TituloLogin = new java.awt.Label();
        txtIdLogin = new javax.swing.JTextField();
        btnLogin = new javax.swing.JButton();
        UserLogin = new javax.swing.JLabel();
        UserLogin1 = new javax.swing.JLabel();
        pswLogin = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TituloLogin.setAlignment(java.awt.Label.CENTER);
        TituloLogin.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        TituloLogin.setText("Log in");

        btnLogin.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnLogin.setText("Ingresa");
        btnLogin.addActionListener(this::btnLoginActionPerformed);

        UserLogin.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        UserLogin.setText("Contraseña");

        UserLogin1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        UserLogin1.setText("ID Empleado");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(199, 199, 199)
                .addComponent(TituloLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 407, Short.MAX_VALUE)
                .addGap(177, 177, 177))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(UserLogin1, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE)
                    .addComponent(UserLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIdLogin)
                    .addComponent(pswLogin)
                    .addComponent(btnLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(238, 238, 238))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(TituloLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(UserLogin1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtIdLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(UserLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pswLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(135, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed

        // 1. Obtener los datos (usando getPassword para el psw)
        String usuario = txtIdLogin.getText();
        String contrasena = new String(pswLogin.getPassword());

        // Validar que los campos no estén vacíos antes de ir a la BD
        if (usuario.isEmpty() || contrasena.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, llene todos los campos");
            txtIdLogin.setText("");
            pswLogin.setText("");
            txtIdLogin.requestFocusInWindow();
            return;
        }

        HMC_Conexion con = new HMC_Conexion();

        if (con.validarUsuario(usuario, contrasena)) {
            // Login exitoso
            HMC_Principal miPrincipal = new HMC_Principal();
            this.dispose(); // Cierra el login

            miPrincipal.setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
            miPrincipal.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Usuario y/o contraseña incorrecto(s)");
            txtIdLogin.setText("");
            pswLogin.setText("");
            txtIdLogin.requestFocusInWindow();
        }


    }//GEN-LAST:event_btnLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new HMC_Login().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Label TituloLogin;
    private javax.swing.JLabel UserLogin;
    private javax.swing.JLabel UserLogin1;
    public javax.swing.JButton btnLogin;
    public javax.swing.JPasswordField pswLogin;
    public javax.swing.JTextField txtIdLogin;
    // End of variables declaration//GEN-END:variables
}
