/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package HMC_Vista;

import HMC_Modelo.HMC_Conexion;
import java.util.HashSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Benjamin
 */
public class HMC_Nomina extends javax.swing.JPanel {

    /**
     * Creates new form HMC_Nomina
     */
    public HMC_Nomina() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnNuevoNom = new javax.swing.JButton();
        btnEliminarNom = new javax.swing.JButton();
        btnGuardarNom = new javax.swing.JButton();
        btnEditarNom = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtNombreNom = new javax.swing.JTextField();
        txtIdNom = new javax.swing.JTextField();
        txtPaternoNom = new javax.swing.JTextField();
        txtMaternoNom = new javax.swing.JTextField();
        txtInicioPNom = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtFinPNom = new javax.swing.JTextField();
        txtSueldoBaseNom = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtBonoNom = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtDesNom = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        txtTotPagNom = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        txtFechaPagoNom = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtIdEmpleadoNom = new javax.swing.JTextField();
        label1 = new java.awt.Label();
        btnBuscaNom = new javax.swing.JButton();

        btnNuevoNom.setText("NUEVO");
        btnNuevoNom.addActionListener(this::btnNuevoNomActionPerformed);

        btnEliminarNom.setForeground(new java.awt.Color(255, 51, 51));
        btnEliminarNom.setText("ELIMINAR");
        btnEliminarNom.setEnabled(false);
        btnEliminarNom.addActionListener(this::btnEliminarNomActionPerformed);

        btnGuardarNom.setText("GUARDAR");
        btnGuardarNom.setEnabled(false);
        btnGuardarNom.addActionListener(this::btnGuardarNomActionPerformed);

        btnEditarNom.setText("EDITAR");
        btnEditarNom.setEnabled(false);
        btnEditarNom.addActionListener(this::btnEditarNomActionPerformed);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Nomina");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("ID NOMINA");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Nombre");

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Apellido Paterno");

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Apellido materno");

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("Inicio de periodo");

        txtNombreNom.setEditable(false);

        txtPaternoNom.setEditable(false);

        txtMaternoNom.setEditable(false);

        txtInicioPNom.setEditable(false);

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel13.setText("Fin de periodo");

        txtFinPNom.setEditable(false);

        txtSueldoBaseNom.setEditable(false);

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel14.setText("Sueldo base");

        txtBonoNom.setEditable(false);

        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel16.setText("Bonos");

        txtDesNom.setEditable(false);

        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel22.setText("Descuentos");

        txtTotPagNom.setEditable(false);

        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel23.setText("Total pagado");

        txtFechaPagoNom.setEditable(false);

        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel24.setText("Fecha de pago");

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("ID EMPLEADO");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFechaPagoNom))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTotPagNom))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDesNom))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBonoNom))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSueldoBaseNom))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFinPNom))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtInicioPNom, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(231, 231, 231))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtNombreNom)
                                    .addComponent(txtPaternoNom, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtIdNom, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtMaternoNom, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtIdEmpleadoNom, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(30, 30, 30))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIdNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(8, 8, 8)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIdEmpleadoNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombreNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtPaternoNom))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtMaternoNom, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtInicioPNom))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtFinPNom))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtSueldoBaseNom))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtBonoNom))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtDesNom))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtTotPagNom))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtFechaPagoNom))
                .addGap(71, 71, 71))
        );

        label1.setText("Puede busacar por ID.");

        btnBuscaNom.setText("BUSCAR");
        btnBuscaNom.addActionListener(this::btnBuscaNomActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1543, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNuevoNom, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscaNom, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGuardarNom, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminarNom, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditarNom, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(399, 399, 399))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(btnBuscaNom, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(btnNuevoNom, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(btnEditarNom, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(btnGuardarNom, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(btnEliminarNom))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(126, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Método para transformar AAAA-MM-DD HH:mm:ss a DD/MM/AAAA
    private String formatearFecha(String fechaBD) {
        if (fechaBD.isEmpty()) {
            return "";
        }
        try {
            // 1. Quitamos la hora si existe (cortamos por el espacio)
            String soloFecha = fechaBD.split(" ")[0];
            // 2. Dividimos los componentes del año-mes-dia
            String partes[] = soloFecha.split("-");
            if (partes.length == 3) {
                // 3. Reordenamos a DD/MM/AAAA
                return partes[2] + "/" + partes[1] + "/" + partes[0];
            }
        } catch (Exception e) {
            return fechaBD; // Si algo falla, devuelve la original
        }
        return fechaBD;
    }

    private void btnNuevoNomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoNomActionPerformed
        btnBuscaNom.setEnabled(false);
        btnEditarNom.setEnabled(false);
        btnEliminarNom.setEnabled(false);
        btnGuardarNom.setEnabled(true);
        btnNuevoNom.setEnabled(true);

        txtIdNom.setEnabled(false);
        txtIdEmpleadoNom.setEnabled(true);
        txtNombreNom.setEnabled(false);
        txtPaternoNom.setEnabled(false);
        txtMaternoNom.setEnabled(false);
        txtInicioPNom.setEnabled(true);
        txtFinPNom.setEnabled(true);
        txtSueldoBaseNom.setEnabled(true);
        txtBonoNom.setEnabled(true);
        txtDesNom.setEnabled(true);
        txtTotPagNom.setEnabled(true);
        txtFechaPagoNom.setEnabled(true);

        txtInicioPNom.setEditable(true);
        txtFinPNom.setEditable(true);
        txtSueldoBaseNom.setEditable(true);
        txtBonoNom.setEditable(true);
        txtDesNom.setEditable(true);
        txtTotPagNom.setEditable(true);
        txtFechaPagoNom.setEditable(true);

        txtIdNom.setText("");
        txtIdEmpleadoNom.setText("");
        txtNombreNom.setText("");
        txtPaternoNom.setText("");
        txtMaternoNom.setText("");
        txtInicioPNom.setText("");
        txtFinPNom.setText("");
        txtSueldoBaseNom.setText("");
        txtBonoNom.setText("");
        txtDesNom.setText("");
        txtTotPagNom.setText("");
        txtFechaPagoNom.setText("");
        txtIdEmpleadoNom.requestFocusInWindow();


    }//GEN-LAST:event_btnNuevoNomActionPerformed

    private void btnEliminarNomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarNomActionPerformed

    }//GEN-LAST:event_btnEliminarNomActionPerformed

    private void btnGuardarNomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarNomActionPerformed

        try {
            // =========================
            // 1. DATOS GENERALES
            // =========================
            int id_empleado = parseEnteroSeguro(txtIdEmpleadoNom.getText().trim());
            String inicio = txtInicioPNom.getText().trim();
            String fin = txtFinPNom.getText().trim();
            Double sueldoBase = parseDoubleSeguro(txtSueldoBaseNom.getText().trim());
            Double bono = parseDoubleSeguro(txtBonoNom.getText().trim());
            Double descuento = parseDoubleSeguro(txtDesNom.getText().trim());
            Double totalPagado = parseDoubleSeguro(txtTotPagNom.getText().trim());
            String fechaPago = txtFechaPagoNom.getText().trim();

            // =========================
            // 2. VALIDACIÓN BÁSICA
            // =========================
            if (inicio.isEmpty() || fin.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Las fechas de inicio y fin son obligatorias");
                return;
            }

            // =========================
            // 3. PARSEO SEGURO
            // =========================
            double salario = parseDoubleSeguro(txtSueldoBaseNom.getText());

            if (salario < 0) {
                JOptionPane.showMessageDialog(this, "Salario inválido");
                return;
            }

            HMC_Conexion con = new HMC_Conexion();
            boolean exito = false;

            // =========================
            // 4. DEFINIR OPERACIÓN
            // =========================
            boolean esNuevo = txtIdNom.getText().trim().isEmpty();

            // =========================
            // 5. INSERT
            // =========================
            if (esNuevo) {

                System.out.println("Nueva nomina");

                int idEmpleadoNomina = parseEnteroSeguro(txtIdEmpleadoNom.getText());

                if (idEmpleadoNomina <= 0) {
                    JOptionPane.showMessageDialog(this, "ID Empleado debe ser válido");
                    return;
                }

                exito = con.insertarNomina(
                        idEmpleadoNomina, inicio, fin,
                        sueldoBase, bono, descuento, totalPagado,
                        fechaPago
                );

                if (exito) {
                    JOptionPane.showMessageDialog(this, "Nomina Creada con exito.");
                }

            } else {
                // =========================
                // 6. UPDATE
                // =========================

                System.out.println("Estas EDITANDO un usuario");

                int idExistente = parseEnteroSeguro(txtIdNom.getText());

                if (idExistente <= 0) {
                    JOptionPane.showMessageDialog(this, "ID inválido");
                    return;
                }

                exito = con.actualizarNomina(
                        id_empleado, inicio, fin,
                        sueldoBase, bono, descuento, totalPagado,
                        fechaPago, idExistente
                );

                if (exito) {
                    JOptionPane.showMessageDialog(this, "Nomina ID: " + idExistente + " actualizada.");
                    btnEditarNom.setEnabled(false);
                }
            }

            // =========================
            // 7. LIMPIAR FORMULARIO
            // =========================
            if (exito) {
                resetearFormulario();
            }

        } catch (Exception e) {

            JOptionPane.showMessageDialog(
                    this,
                    "Error al guardar: " + e.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE
            );

            e.printStackTrace();
        }


    }//GEN-LAST:event_btnGuardarNomActionPerformed

    private void btnEditarNomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarNomActionPerformed

    }//GEN-LAST:event_btnEditarNomActionPerformed

    private void btnBuscaNomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscaNomActionPerformed
        HMC_Conexion con = new HMC_Conexion();

        int iDNominaBuscar = Integer.parseInt(txtIdNom.getText());
        String nominaEncontrada = con.buscarNominaId(iDNominaBuscar);

        if (nominaEncontrada != null && !nominaEncontrada.isEmpty()) {
            String nominaEncontradaBD[] = nominaEncontrada.split("!");

            java.util.function.Function<String, String> limpiar = (str)
                    -> (str == null || str.equals("null")) ? "" : str;

            txtIdNom.setText(limpiar.apply(nominaEncontradaBD[0]));
            txtIdEmpleadoNom.setText(limpiar.apply(nominaEncontradaBD[1]));
            txtNombreNom.setText(limpiar.apply(nominaEncontradaBD[2]));
            txtPaternoNom.setText(limpiar.apply(nominaEncontradaBD[3]));
            txtMaternoNom.setText(limpiar.apply(nominaEncontradaBD[4]));
            txtInicioPNom.setText(formatearFecha(limpiar.apply(nominaEncontradaBD[5])));
            txtFinPNom.setText(formatearFecha(limpiar.apply(nominaEncontradaBD[6])));
            txtSueldoBaseNom.setText(limpiar.apply(nominaEncontradaBD[7]));
            txtBonoNom.setText(limpiar.apply(nominaEncontradaBD[8]));
            txtDesNom.setText(limpiar.apply(nominaEncontradaBD[9]));
            txtTotPagNom.setText(limpiar.apply(nominaEncontradaBD[10]));
            //txtFechaPagoNom.setText(limpiar.apply(nominaEncontradaBD[10]));    
            txtFechaPagoNom.setText(formatearFecha(limpiar.apply(nominaEncontradaBD[11])));

            //Activo los botones para poder editar o eliminar el valor obtenido.
            btnEditarNom.setEnabled(true);
            btnEliminarNom.setEnabled(true);

        } else {
            JOptionPane.showMessageDialog(this, "Número de ID de nomina no encontrada.");
            txtIdNom.setText("");
            txtIdEmpleadoNom.setText("");
            txtNombreNom.setText("");
            txtPaternoNom.setText("");
            txtMaternoNom.setText("");
            txtInicioPNom.setText("");
            txtFinPNom.setText("");
            txtSueldoBaseNom.setText("");
            txtBonoNom.setText("");
            txtDesNom.setText("");
            txtTotPagNom.setText("");
            txtFechaPagoNom.setText("");
            txtIdNom.requestFocusInWindow();

        }

    }//GEN-LAST:event_btnBuscaNomActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscaNom;
    private javax.swing.JButton btnEditarNom;
    private javax.swing.JButton btnEliminarNom;
    private javax.swing.JButton btnGuardarNom;
    private javax.swing.JButton btnNuevoNom;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private java.awt.Label label1;
    private javax.swing.JTextField txtBonoNom;
    private javax.swing.JTextField txtDesNom;
    private javax.swing.JTextField txtFechaPagoNom;
    private javax.swing.JTextField txtFinPNom;
    private javax.swing.JTextField txtIdEmpleadoNom;
    private javax.swing.JTextField txtIdNom;
    private javax.swing.JTextField txtInicioPNom;
    private javax.swing.JTextField txtMaternoNom;
    private javax.swing.JTextField txtNombreNom;
    private javax.swing.JTextField txtPaternoNom;
    private javax.swing.JTextField txtSueldoBaseNom;
    private javax.swing.JTextField txtTotPagNom;
    // End of variables declaration//GEN-END:variables

    private int parseEnteroSeguro(String valor) {
        try {
            if (valor == null || valor.trim().isEmpty()) {
                return 0;
            }
            return Integer.parseInt(valor.trim());
        } catch (NumberFormatException e) {
            return -1;
        }
    }

    private double parseDoubleSeguro(String valor) {
        try {
            if (valor == null || valor.trim().isEmpty()) {
                return 0;
            }
            return Double.parseDouble(valor.trim());
        } catch (NumberFormatException e) {
            return -1;
        }
    }

    public void resetearFormulario() {
        // 1. Limpiar todos los textos
        txtIdNom.setText("");
        txtIdEmpleadoNom.setText("");
        txtNombreNom.setText("");
        txtPaternoNom.setText("");
        txtMaternoNom.setText("");
        txtInicioPNom.setText("");
        txtFinPNom.setText("");
        txtSueldoBaseNom.setText("");
        txtBonoNom.setText("");
        txtDesNom.setText("");
        txtTotPagNom.setText("");
        txtFechaPagoNom.setText("");
        txtIdNom.setText("");

        // 2. Bloquear los campos de texto (para que no escriban sin darle a 'Nuevo')
        
        txtIdNom.setEnabled(true); 
        txtIdEmpleadoNom.setEnabled(false);
        txtNombreNom.setEnabled(false);
        txtPaternoNom.setEnabled(false);
        txtMaternoNom.setEnabled(false);
        txtInicioPNom.setEnabled(false);
        txtFinPNom.setEnabled(false);
        txtSueldoBaseNom.setEnabled(false);
        txtBonoNom.setEnabled(false);
        txtDesNom.setEnabled(false);
        txtTotPagNom.setEnabled(false);
        txtFechaPagoNom.setEnabled(false);

        // 3. Gestionar los botones
        btnNuevoNom.setEnabled(true);    // Puede crear uno nuevo
        btnBuscaNom.setEnabled(true);   // Puede buscar
        btnGuardarNom.setEnabled(false); // No puede guardar nada vacío

        // 4. Cursor al campo de búsqueda
        txtIdNom.requestFocusInWindow();
    }
}
